### ISSUE TITLE
xcode 6.4 crash

### ISSUE THREAD

**Issue by GWesley** [bumaociyuan/JSFormatter-Xcode#1]

**Comment by bumaociyuan** [comment]
Xcode Version 6.4 (6E35b)
没有crash

![a0550d55-ed10-41b6-8012-52c9aed84631](https://cloud.githubusercontent.com/assets/4977911/9761627/90e3483e-5730-11e5-9ec1-8417a8553e6f.png)
这个地方要点Load Bundle

@GWesley 你是怎么crash的？
