### ISSUE TITLE
xcode7不好用啊

### ISSUE THREAD

**Issue by jackiedeng** [bumaociyuan/JSFormatter-Xcode#2]
xcode7 使用之后所有代码全部清除，啥也没了

**Comment by bumaociyuan** [comment]
确定安装了 node 和jsbeautify么？

尝试移除，再重新安装

**Comment by jackiedeng** [comment]
是我忘记装jsbeautify了，请问怎么绑定快捷键呢，我在设定快捷键里貌似没有找到JSFormatter哦

**Comment by bumaociyuan** [comment]
@jackiedeng https://support.apple.com/kb/ph3957?locale=en_US
