### ISSUE TITLE
JSFormatter delete all codes?

### ISSUE THREAD

**Issue by litt1e-p** [bumaociyuan/JSFormatter-Xcode#4]
JSFormatter delete all codes when I click Format Active JsFile in my Js/css/html files? Did I use it in wrong way? I install via Alcatraz. My environment: Xcode 7.3, swift2.2

**Comment by bumaociyuan** [comment]
@litt1e-p you need install Node.js and js-beautify first

**Comment by litt1e-p** [comment]
thanks, It works now!
