### ISSUE TITLE
JSFormatter didn't show

### ISSUE THREAD

**Issue by hellojuny** [bumaociyuan/JSFormatter-Xcode#5]
I have installed Alcatraz.xcplugin and JSFormatter.xcplugin,but I didn't watch the JSFormatter under the menu 'EDIT', My Xcode's version is 8.0，can you help me?

**Comment by bumaociyuan** [comment]
Hi. @hellojuny Check this link https://github.com/alcatraz/Alcatraz/issues/475

This tool may help you https://github.com/inket/update_xcode_plugins
