### ISSUE TITLE
why xcode crash

### ISSUE THREAD

**Issue by coooliang** [bumaociyuan/JSFormatter-Xcode#6]
I'm used Alcatraz install JSFormatter
but when I click Edit-->JSFormatter-->Format Active JS File  was crash

my mac and xcode version is :
macOS High Sierra10.13.6
Xcode Version 9.4.1

**Comment by bumaociyuan** [comment]
Xcode9 苹果把Xcode重构了一下，我已经没有在维护这个项目了，建议你用VSCode编辑js
